services:
  backend:
    image: gitregistry.cnpem.br/beamlines/manaca/gui/arara/backend:v1
    build:
      context: ./app
      image: arara_backend
    container_name: backend
    logging:
      driver: "k8s-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
      - ${BASE_DIR}:${BASE_DIR}

  frontend:
    image: gitregistry.cnpem.br/beamlines/manaca/gui/arara/frontend:v1
    build:
      context: ./image-viewer-web
      image: arara_frontend
    container_name: frontend
    logging:
      driver: "k8s-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8443:443"
    volumes:
      - ./image-viewer-web:/app
      - /home/ABTLUS/pedro.benetton/opt_keys/certificates:/certificates
    depends_on:
      - backend

